# Generated by Django 5.1.15 on 2026-05-12 19:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotStatus",
            fields=[
                (
                    "id",
                    models.SmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("paused", models.BooleanField(default=False)),
                (
                    "last_heartbeat",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GridLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_index", models.IntegerField(unique=True)),
                (
                    "target_buy_price",
                    models.DecimalField(decimal_places=12, max_digits=28),
                ),
                (
                    "current_buy_order_id",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("awaiting_fill", "Awaiting fill"),
                            ("filled", "Filled"),
                        ],
                        default="idle",
                        max_length=16,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["level_index"],
            },
        ),
        migrations.CreateModel(
            name="StrategyConfig",
            fields=[
                (
                    "id",
                    models.SmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("symbol", models.CharField(default="BTCUSDT", max_length=32)),
                (
                    "grid_mode",
                    models.CharField(
                        choices=[
                            ("absolute", "Absolute (USDT step)"),
                            ("percent", "Percent step"),
                        ],
                        default="percent",
                        max_length=16,
                    ),
                ),
                (
                    "grid_step",
                    models.DecimalField(
                        decimal_places=12,
                        default=Decimal("0.005"),
                        max_digits=28,
                    ),
                ),
                (
                    "order_qty_quote",
                    models.DecimalField(
                        decimal_places=12, default=Decimal("10"), max_digits=28
                    ),
                ),
                (
                    "top_anchor",
                    models.DecimalField(
                        blank=True, decimal_places=12, max_digits=28, null=True
                    ),
                ),
                (
                    "min_profit_quote",
                    models.DecimalField(
                        decimal_places=12,
                        default=Decimal("0.01"),
                        max_digits=28,
                    ),
                ),
                (
                    "maker_fee",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0.001"),
                        max_digits=10,
                    ),
                ),
                ("max_open_orders", models.PositiveIntegerField(default=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.BigIntegerField(unique=True)),
                ("label", models.CharField(blank=True, max_length=64)),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exec_id", models.CharField(max_length=64, unique=True)),
                ("order_id", models.CharField(db_index=True, max_length=64)),
                ("symbol", models.CharField(max_length=32)),
                (
                    "side",
                    models.CharField(
                        choices=[("Buy", "Buy"), ("Sell", "Sell")],
                        max_length=8,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=12, max_digits=28),
                ),
                ("qty", models.DecimalField(decimal_places=12, max_digits=28)),
                ("fee", models.DecimalField(decimal_places=12, max_digits=28)),
                ("fee_coin", models.CharField(blank=True, max_length=16)),
                ("executed_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-executed_at"],
                "indexes": [
                    models.Index(
                        fields=["-executed_at"],
                        name="trading_exe_execute_cb8945_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_index", models.IntegerField()),
                (
                    "entry_price",
                    models.DecimalField(decimal_places=12, max_digits=28),
                ),
                ("qty", models.DecimalField(decimal_places=12, max_digits=28)),
                (
                    "fees_in",
                    models.DecimalField(
                        decimal_places=12, default=Decimal("0"), max_digits=28
                    ),
                ),
                (
                    "fees_out",
                    models.DecimalField(
                        decimal_places=12, default=Decimal("0"), max_digits=28
                    ),
                ),
                ("tp_order_id", models.CharField(blank=True, max_length=64)),
                (
                    "tp_price",
                    models.DecimalField(
                        blank=True, decimal_places=12, max_digits=28, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(
                        decimal_places=12, default=Decimal("0"), max_digits=28
                    ),
                ),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-opened_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "level_index"],
                        name="trading_pos_status_530703_idx",
                    ),
                    models.Index(
                        fields=["status", "opened_at"],
                        name="trading_pos_status_9e0ef0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompensationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profit_applied",
                    models.DecimalField(decimal_places=12, max_digits=28),
                ),
                (
                    "new_tp_price",
                    models.DecimalField(decimal_places=12, max_digits=28),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compensated_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensations_received",
                        to="trading.position",
                    ),
                ),
                (
                    "profitable_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensations_given",
                        to="trading.position",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
