# Generated by Django 5.1.15 on 2026-07-05 13:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='compensation_credit',
            field=models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=28),
        ),
    ]
