# Generated by Django 5.1.15 on 2026-07-05 14:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0002_position_compensation_credit"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategyconfig",
            name="tp_step",
            field=models.DecimalField(
                decimal_places=12,
                default=Decimal("0.00005"),
                help_text="Absolute price offset above entry for the take-profit.",
                max_digits=28,
            ),
        ),
    ]
