# Generated by Django 5.1.15 on 2026-07-06 09:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0003_strategyconfig_tp_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="filled_qty",
            field=models.DecimalField(decimal_places=12, default=Decimal("0"), max_digits=28),
        ),
        migrations.AddField(
            model_name="position",
            name="sell_value",
            field=models.DecimalField(decimal_places=12, default=Decimal("0"), max_digits=28),
        ),
    ]
