# Generated by Django 5.1.15 on 2026-07-07 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0005_strategyconfig_taker_fee"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.SmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notify_errors", models.BooleanField(default=True)),
                ("notify_closed", models.BooleanField(default=True)),
                ("notify_compensation", models.BooleanField(default=True)),
                ("notify_opened", models.BooleanField(default=True)),
                ("notify_order_placed", models.BooleanField(default=True)),
                ("digest_enabled", models.BooleanField(default=True)),
                (
                    "digest_time_utc",
                    models.TimeField(default=datetime.time(19, 0)),
                ),
                ("digest_last_sent", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
