# Generated by Django 5.1.15 on 2026-07-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0006_notificationsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="botstatus",
            name="applied_grid_step",
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=28, null=True),
        ),
        migrations.AddField(
            model_name="botstatus",
            name="applied_order_qty",
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=28, null=True),
        ),
    ]
