# Generated by Django 5.1.15 on 2026-07-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0007_botstatus_applied_grid_step_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="notify_order_cancelled",
            field=models.BooleanField(default=True),
        ),
    ]
