# Generated by Django 5.1.15 on 2026-07-18 19:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0008_notificationsettings_notify_order_cancelled"),
    ]

    operations = [
        migrations.AddField(
            model_name="botstatus",
            name="pending_credit",
            field=models.DecimalField(
                decimal_places=12, default=Decimal("0"), max_digits=28
            ),
        ),
    ]
